accountapp/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(template_name='articleapp/list.html'), name='list'),
    path('create/', ArticleCreateView.as_view(template_name='articleapp/create.html'), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(template_name='articleapp/detail.html'), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(template_name='articleapp/update.html'), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(template_name='articleapp/delete.html'), name='delete'),

]

pragmatic/urls.py
# noinspection GrazieInspection
"""pragmatic URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectListView, ProjectDetailView

app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family : 'NanumSquareR'">

    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
    <div class="pragmatic_footer">
        <div class="pragmatic_footer_button">
            <span>공지사항</span> |
            <span>제휴문의</span> |
            <span>서비스 소개</span>
        </div>
        <div style="margin-top : 1rem;">
                <h6 class="pragmatic_logo">pragmatic</h6>
        </div>

    </div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pragmatic</title>

    <!--    BOOTSTRAP LINK-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <!-- GOOGLE FONTS LINK -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

    <!-- GOOGLE MATERIAL ICONS -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

    <!-- DEFAULT CSS LINK -->
    <LINK rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family : 'NanumSquareB';
            src : local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }

        @font-face {
        font-family : 'NanumSquareEB';
        src : local('NanumSquareEB'),
        url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }

        @font-face {
        font-family : 'NanumSquareR';
        src : local('NanumSquareL'),
        url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }

        @font-face {
        font-family : 'NanumSquareEB';
        src : local('NanumSquareEB'),
        url("{% static 'fonts/NanumSquareEB.otf ' %}") format("opentype");
        }

    </style>


</head>

templates/header.html
    <div class="pragmatic_header">
        <div>
            <h1 class="pragmatic_logo">Pragmatic</h1>
        </div>
        <div class="pragmatic_header_navbar">
            <a href ="{% url 'articleapp:list' %}" class="pragmatic_header_nav">
                <span>Articles</span>
            </a>
            <a href ="{% url 'projectapp:list' %}" class="pragmatic_header_nav">
                <span>Projects</span>
            </a>
            <a href ="{% url 'subscribeapp:list' %}" class="pragmatic_header_nav">
                <span>Subscription</span>
            </a>
            {% if not user.is_authenticated %}
            <a href ="{% url 'accountapp:login' %}?next={{ request.path }}" class="pragmatic_header_nav">
                <span>Login</span>
            </a>
            <a href ="{% url 'accountapp:create' %}" class="pragmatic_header_nav">
                <span>SignUp</span>
            </a>
            {% else %}
            <a href ="{% url 'accountapp:detail' pk=user.pk %}" class="pragmatic_header_nav">
                <span>MyPage</span>
            </a>
            <a href ="{% url 'accountapp:logout' %}?next={{ request.path }}" class="pragmatic_header_nav">
                <span>Logout</span>
            </a>
            {% endif %}
        </div>
    </div>